#!/usr/bin/env node
// Packs Code.gs + Index/Styles/App.html into ONE file, dist/Code.gs, so a
// teacher pastes a single file into Apps Script. The HTML is embedded as
// strings and served through EMBEDDED_HTML (see doGet/include in Code.gs).
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const code = read('apps-script/Code.gs');
const html = { Index: read('apps-script/Index.html'), Styles: read('apps-script/Styles.html'), App: read('apps-script/App.html') };
// JSON.stringify gives a valid JS string literal; break "</script>" so the
// embedded App.html can never terminate a script tag if viewed as HTML.
const lit = s => JSON.stringify(s).replace(/<\/script>/g, '<\\/script>');
const out = code +
  '\n\n// =============================================================\n' +
  '// Embedded web-app files (generated by dev/build-single.js — do not edit here;\n' +
  '// edit apps-script/*.html and rebuild).\n' +
  '// =============================================================\n' +
  'EMBEDDED_HTML = {\n' +
  '  Index: ' + lit(html.Index) + ',\n' +
  '  Styles: ' + lit(html.Styles) + ',\n' +
  '  App: ' + lit(html.App) + '\n' +
  '};\n';
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist/Code.gs'), out);
console.log('Wrote dist/Code.gs', `(${(out.length / 1024).toFixed(0)} KB, ${out.split('\n').length} lines)`);
